### ISSUE TITLE
Worldguard worked on 1.13pre7 but fails to load on 1.13

### ISSUE THREAD

**Issue by gerardvanschip** [SpigotMC/SpigotCraft#418]
- [x] Bug exists on current Spigot version (1.13)

The worldguard.jar supplied in the post on the website worked fine on 1.13pre7 but refuses to load on the full 1.13 release. Below is the error. The server is clean, I removed all 1.12.2 files. This is just git-Spigot-ed1cec9-4e2f571 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT) with Discord, worldguard and CMI.

Worldguard came from here:
https://github.com/SpigotMC/SpigotCraft/tree/master/plugins

[09:42:04] [Server thread/ERROR]: Could not load 'plugins/WorldGuard.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [custom.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:313) [custom.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:213) [custom.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [custom.jar:git-Spigot-ed1cec9-4e2f571]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_65]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.CommandPermissionsException
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_65]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	... 6 more

**Comment by md-5** [comment]
We don't actually support these plugins, just use them on our server.

For what its worth, it does still load fine for me on 1.13 release.
I suggest checking your log for other errors or redownloading.
